/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProviderSignupRouteImport } from './routes/provider-signup'
import { Route as ProviderLoginRouteImport } from './routes/provider-login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BecomeAProviderRouteImport } from './routes/become-a-provider'
import { Route as BecomeADriverRouteImport } from './routes/become-a-driver'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedSendDeliveryRouteImport } from './routes/_authenticated/send-delivery'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBusinessPortalRouteImport } from './routes/_authenticated/business-portal'
import { Route as AuthenticatedProviderIndexRouteImport } from './routes/_authenticated/provider.index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedProviderSetupRouteImport } from './routes/_authenticated/provider.setup'
import { Route as AuthenticatedMessagesBookingIdRouteImport } from './routes/_authenticated/messages.$bookingId'
import { Route as AuthenticatedDeliveriesIdRouteImport } from './routes/_authenticated/deliveries.$id'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings.$id'
import { Route as AuthenticatedBookCategoryRouteImport } from './routes/_authenticated/book.$category'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/admin.commissions'
import { Route as AuthenticatedAdminReconciliationIndexRouteImport } from './routes/_authenticated/admin.reconciliation.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAdminReconciliationProviderProviderIdRouteImport } from './routes/_authenticated/admin.reconciliation.provider.$providerId'
import { Route as AuthenticatedAdminReconciliationBookingBookingIdRouteImport } from './routes/_authenticated/admin.reconciliation.booking.$bookingId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderSignupRoute = ProviderSignupRouteImport.update({
  id: '/provider-signup',
  path: '/provider-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderLoginRoute = ProviderLoginRouteImport.update({
  id: '/provider-login',
  path: '/provider-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAProviderRoute = BecomeAProviderRouteImport.update({
  id: '/become-a-provider',
  path: '/become-a-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeADriverRoute = BecomeADriverRouteImport.update({
  id: '/become-a-driver',
  path: '/become-a-driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSendDeliveryRoute =
  AuthenticatedSendDeliveryRouteImport.update({
    id: '/send-delivery',
    path: '/send-delivery',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBusinessPortalRoute =
  AuthenticatedBusinessPortalRouteImport.update({
    id: '/business-portal',
    path: '/business-portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProviderIndexRoute =
  AuthenticatedProviderIndexRouteImport.update({
    id: '/provider/',
    path: '/provider/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProviderSetupRoute =
  AuthenticatedProviderSetupRouteImport.update({
    id: '/provider/setup',
    path: '/provider/setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesBookingIdRoute =
  AuthenticatedMessagesBookingIdRouteImport.update({
    id: '/messages/$bookingId',
    path: '/messages/$bookingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeliveriesIdRoute =
  AuthenticatedDeliveriesIdRouteImport.update({
    id: '/deliveries/$id',
    path: '/deliveries/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookCategoryRoute =
  AuthenticatedBookCategoryRouteImport.update({
    id: '/book/$category',
    path: '/book/$category',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/admin/providers',
    path: '/admin/providers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/admin/commissions',
    path: '/admin/commissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReconciliationIndexRoute =
  AuthenticatedAdminReconciliationIndexRouteImport.update({
    id: '/admin/reconciliation/',
    path: '/admin/reconciliation/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminReconciliationProviderProviderIdRoute =
  AuthenticatedAdminReconciliationProviderProviderIdRouteImport.update({
    id: '/admin/reconciliation/provider/$providerId',
    path: '/admin/reconciliation/provider/$providerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReconciliationBookingBookingIdRoute =
  AuthenticatedAdminReconciliationBookingBookingIdRouteImport.update({
    id: '/admin/reconciliation/booking/$bookingId',
    path: '/admin/reconciliation/booking/$bookingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-driver': typeof BecomeADriverRoute
  '/become-a-provider': typeof BecomeAProviderRoute
  '/business': typeof BusinessRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/provider-login': typeof ProviderLoginRoute
  '/provider-signup': typeof ProviderSignupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/business-portal': typeof AuthenticatedBusinessPortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/send-delivery': typeof AuthenticatedSendDeliveryRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/book/$category': typeof AuthenticatedBookCategoryRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/deliveries/$id': typeof AuthenticatedDeliveriesIdRoute
  '/messages/$bookingId': typeof AuthenticatedMessagesBookingIdRoute
  '/provider/setup': typeof AuthenticatedProviderSetupRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/provider/': typeof AuthenticatedProviderIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/reconciliation/': typeof AuthenticatedAdminReconciliationIndexRoute
  '/admin/reconciliation/booking/$bookingId': typeof AuthenticatedAdminReconciliationBookingBookingIdRoute
  '/admin/reconciliation/provider/$providerId': typeof AuthenticatedAdminReconciliationProviderProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-driver': typeof BecomeADriverRoute
  '/become-a-provider': typeof BecomeAProviderRoute
  '/business': typeof BusinessRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/provider-login': typeof ProviderLoginRoute
  '/provider-signup': typeof ProviderSignupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/business-portal': typeof AuthenticatedBusinessPortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/send-delivery': typeof AuthenticatedSendDeliveryRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/services': typeof ServicesIndexRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/book/$category': typeof AuthenticatedBookCategoryRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/deliveries/$id': typeof AuthenticatedDeliveriesIdRoute
  '/messages/$bookingId': typeof AuthenticatedMessagesBookingIdRoute
  '/provider/setup': typeof AuthenticatedProviderSetupRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/provider': typeof AuthenticatedProviderIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/reconciliation': typeof AuthenticatedAdminReconciliationIndexRoute
  '/admin/reconciliation/booking/$bookingId': typeof AuthenticatedAdminReconciliationBookingBookingIdRoute
  '/admin/reconciliation/provider/$providerId': typeof AuthenticatedAdminReconciliationProviderProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/become-a-driver': typeof BecomeADriverRoute
  '/become-a-provider': typeof BecomeAProviderRoute
  '/business': typeof BusinessRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/provider-login': typeof ProviderLoginRoute
  '/provider-signup': typeof ProviderSignupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/business-portal': typeof AuthenticatedBusinessPortalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/send-delivery': typeof AuthenticatedSendDeliveryRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/book/$category': typeof AuthenticatedBookCategoryRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/deliveries/$id': typeof AuthenticatedDeliveriesIdRoute
  '/_authenticated/messages/$bookingId': typeof AuthenticatedMessagesBookingIdRoute
  '/_authenticated/provider/setup': typeof AuthenticatedProviderSetupRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/provider/': typeof AuthenticatedProviderIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/reconciliation/': typeof AuthenticatedAdminReconciliationIndexRoute
  '/_authenticated/admin/reconciliation/booking/$bookingId': typeof AuthenticatedAdminReconciliationBookingBookingIdRoute
  '/_authenticated/admin/reconciliation/provider/$providerId': typeof AuthenticatedAdminReconciliationProviderProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-a-driver'
    | '/become-a-provider'
    | '/business'
    | '/careers'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/provider-login'
    | '/provider-signup'
    | '/reset-password'
    | '/services'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/business-portal'
    | '/dashboard'
    | '/driver'
    | '/notifications'
    | '/send-delivery'
    | '/workspace'
    | '/services/'
    | '/admin/commissions'
    | '/admin/providers'
    | '/book/$category'
    | '/bookings/$id'
    | '/deliveries/$id'
    | '/messages/$bookingId'
    | '/provider/setup'
    | '/admin/'
    | '/bookings/'
    | '/provider/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/reconciliation/'
    | '/admin/reconciliation/booking/$bookingId'
    | '/admin/reconciliation/provider/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-a-driver'
    | '/become-a-provider'
    | '/business'
    | '/careers'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/provider-login'
    | '/provider-signup'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/business-portal'
    | '/dashboard'
    | '/driver'
    | '/notifications'
    | '/send-delivery'
    | '/workspace'
    | '/services'
    | '/admin/commissions'
    | '/admin/providers'
    | '/book/$category'
    | '/bookings/$id'
    | '/deliveries/$id'
    | '/messages/$bookingId'
    | '/provider/setup'
    | '/admin'
    | '/bookings'
    | '/provider'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/reconciliation'
    | '/admin/reconciliation/booking/$bookingId'
    | '/admin/reconciliation/provider/$providerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/become-a-driver'
    | '/become-a-provider'
    | '/business'
    | '/careers'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/provider-login'
    | '/provider-signup'
    | '/reset-password'
    | '/services'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/business-portal'
    | '/_authenticated/dashboard'
    | '/_authenticated/driver'
    | '/_authenticated/notifications'
    | '/_authenticated/send-delivery'
    | '/_authenticated/workspace'
    | '/services/'
    | '/_authenticated/admin/commissions'
    | '/_authenticated/admin/providers'
    | '/_authenticated/book/$category'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/deliveries/$id'
    | '/_authenticated/messages/$bookingId'
    | '/_authenticated/provider/setup'
    | '/_authenticated/admin/'
    | '/_authenticated/bookings/'
    | '/_authenticated/provider/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/reconciliation/'
    | '/_authenticated/admin/reconciliation/booking/$bookingId'
    | '/_authenticated/admin/reconciliation/provider/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BecomeADriverRoute: typeof BecomeADriverRoute
  BecomeAProviderRoute: typeof BecomeAProviderRoute
  BusinessRoute: typeof BusinessRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProviderLoginRoute: typeof ProviderLoginRoute
  ProviderSignupRoute: typeof ProviderSignupRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-signup': {
      id: '/provider-signup'
      path: '/provider-signup'
      fullPath: '/provider-signup'
      preLoaderRoute: typeof ProviderSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-login': {
      id: '/provider-login'
      path: '/provider-login'
      fullPath: '/provider-login'
      preLoaderRoute: typeof ProviderLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-provider': {
      id: '/become-a-provider'
      path: '/become-a-provider'
      fullPath: '/become-a-provider'
      preLoaderRoute: typeof BecomeAProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-driver': {
      id: '/become-a-driver'
      path: '/become-a-driver'
      fullPath: '/become-a-driver'
      preLoaderRoute: typeof BecomeADriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/send-delivery': {
      id: '/_authenticated/send-delivery'
      path: '/send-delivery'
      fullPath: '/send-delivery'
      preLoaderRoute: typeof AuthenticatedSendDeliveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/business-portal': {
      id: '/_authenticated/business-portal'
      path: '/business-portal'
      fullPath: '/business-portal'
      preLoaderRoute: typeof AuthenticatedBusinessPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/provider/': {
      id: '/_authenticated/provider/'
      path: '/provider'
      fullPath: '/provider/'
      preLoaderRoute: typeof AuthenticatedProviderIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/provider/setup': {
      id: '/_authenticated/provider/setup'
      path: '/provider/setup'
      fullPath: '/provider/setup'
      preLoaderRoute: typeof AuthenticatedProviderSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/$bookingId': {
      id: '/_authenticated/messages/$bookingId'
      path: '/messages/$bookingId'
      fullPath: '/messages/$bookingId'
      preLoaderRoute: typeof AuthenticatedMessagesBookingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries/$id': {
      id: '/_authenticated/deliveries/$id'
      path: '/deliveries/$id'
      fullPath: '/deliveries/$id'
      preLoaderRoute: typeof AuthenticatedDeliveriesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/book/$category': {
      id: '/_authenticated/book/$category'
      path: '/book/$category'
      fullPath: '/book/$category'
      preLoaderRoute: typeof AuthenticatedBookCategoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/commissions': {
      id: '/_authenticated/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reconciliation/': {
      id: '/_authenticated/admin/reconciliation/'
      path: '/admin/reconciliation'
      fullPath: '/admin/reconciliation/'
      preLoaderRoute: typeof AuthenticatedAdminReconciliationIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/reconciliation/provider/$providerId': {
      id: '/_authenticated/admin/reconciliation/provider/$providerId'
      path: '/admin/reconciliation/provider/$providerId'
      fullPath: '/admin/reconciliation/provider/$providerId'
      preLoaderRoute: typeof AuthenticatedAdminReconciliationProviderProviderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reconciliation/booking/$bookingId': {
      id: '/_authenticated/admin/reconciliation/booking/$bookingId'
      path: '/admin/reconciliation/booking/$bookingId'
      fullPath: '/admin/reconciliation/booking/$bookingId'
      preLoaderRoute: typeof AuthenticatedAdminReconciliationBookingBookingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBusinessPortalRoute: typeof AuthenticatedBusinessPortalRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSendDeliveryRoute: typeof AuthenticatedSendDeliveryRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedBookCategoryRoute: typeof AuthenticatedBookCategoryRoute
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedDeliveriesIdRoute: typeof AuthenticatedDeliveriesIdRoute
  AuthenticatedMessagesBookingIdRoute: typeof AuthenticatedMessagesBookingIdRoute
  AuthenticatedProviderSetupRoute: typeof AuthenticatedProviderSetupRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedProviderIndexRoute: typeof AuthenticatedProviderIndexRoute
  AuthenticatedAdminReconciliationIndexRoute: typeof AuthenticatedAdminReconciliationIndexRoute
  AuthenticatedAdminReconciliationBookingBookingIdRoute: typeof AuthenticatedAdminReconciliationBookingBookingIdRoute
  AuthenticatedAdminReconciliationProviderProviderIdRoute: typeof AuthenticatedAdminReconciliationProviderProviderIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBusinessPortalRoute: AuthenticatedBusinessPortalRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSendDeliveryRoute: AuthenticatedSendDeliveryRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
  AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
  AuthenticatedBookCategoryRoute: AuthenticatedBookCategoryRoute,
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedDeliveriesIdRoute: AuthenticatedDeliveriesIdRoute,
  AuthenticatedMessagesBookingIdRoute: AuthenticatedMessagesBookingIdRoute,
  AuthenticatedProviderSetupRoute: AuthenticatedProviderSetupRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedProviderIndexRoute: AuthenticatedProviderIndexRoute,
  AuthenticatedAdminReconciliationIndexRoute:
    AuthenticatedAdminReconciliationIndexRoute,
  AuthenticatedAdminReconciliationBookingBookingIdRoute:
    AuthenticatedAdminReconciliationBookingBookingIdRoute,
  AuthenticatedAdminReconciliationProviderProviderIdRoute:
    AuthenticatedAdminReconciliationProviderProviderIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ServicesRouteChildren {
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BecomeADriverRoute: BecomeADriverRoute,
  BecomeAProviderRoute: BecomeAProviderRoute,
  BusinessRoute: BusinessRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProviderLoginRoute: ProviderLoginRoute,
  ProviderSignupRoute: ProviderSignupRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
