/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BecomeAProviderRouteImport } from './routes/become-a-provider'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProviderRouteImport } from './routes/_authenticated/provider'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedProviderSetupRouteImport } from './routes/_authenticated/provider.setup'
import { Route as AuthenticatedMessagesBookingIdRouteImport } from './routes/_authenticated/messages.$bookingId'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings.$id'
import { Route as AuthenticatedBookCategoryRouteImport } from './routes/_authenticated/book.$category'
import { Route as AuthenticatedAdminReconciliationRouteImport } from './routes/_authenticated/admin.reconciliation'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/admin.commissions'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAdminReconciliationProviderProviderIdRouteImport } from './routes/_authenticated/admin.reconciliation.provider.$providerId'
import { Route as AuthenticatedAdminReconciliationBookingBookingIdRouteImport } from './routes/_authenticated/admin.reconciliation.booking.$bookingId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAProviderRoute = BecomeAProviderRouteImport.update({
  id: '/become-a-provider',
  path: '/become-a-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProviderSetupRoute =
  AuthenticatedProviderSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedMessagesBookingIdRoute =
  AuthenticatedMessagesBookingIdRouteImport.update({
    id: '/messages/$bookingId',
    path: '/messages/$bookingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBookingsRoute,
} as any)
const AuthenticatedBookCategoryRoute =
  AuthenticatedBookCategoryRouteImport.update({
    id: '/book/$category',
    path: '/book/$category',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReconciliationRoute =
  AuthenticatedAdminReconciliationRouteImport.update({
    id: '/admin/reconciliation',
    path: '/admin/reconciliation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/admin/providers',
    path: '/admin/providers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/admin/commissions',
    path: '/admin/commissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminReconciliationProviderProviderIdRoute =
  AuthenticatedAdminReconciliationProviderProviderIdRouteImport.update({
    id: '/provider/$providerId',
    path: '/provider/$providerId',
    getParentRoute: () => AuthenticatedAdminReconciliationRoute,
  } as any)
const AuthenticatedAdminReconciliationBookingBookingIdRoute =
  AuthenticatedAdminReconciliationBookingBookingIdRouteImport.update({
    id: '/booking/$bookingId',
    path: '/booking/$bookingId',
    getParentRoute: () => AuthenticatedAdminReconciliationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-provider': typeof BecomeAProviderRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/provider': typeof AuthenticatedProviderRouteWithChildren
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/reconciliation': typeof AuthenticatedAdminReconciliationRouteWithChildren
  '/book/$category': typeof AuthenticatedBookCategoryRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/messages/$bookingId': typeof AuthenticatedMessagesBookingIdRoute
  '/provider/setup': typeof AuthenticatedProviderSetupRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/reconciliation/booking/$bookingId': typeof AuthenticatedAdminReconciliationBookingBookingIdRoute
  '/admin/reconciliation/provider/$providerId': typeof AuthenticatedAdminReconciliationProviderProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-provider': typeof BecomeAProviderRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/provider': typeof AuthenticatedProviderRouteWithChildren
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/reconciliation': typeof AuthenticatedAdminReconciliationRouteWithChildren
  '/book/$category': typeof AuthenticatedBookCategoryRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/messages/$bookingId': typeof AuthenticatedMessagesBookingIdRoute
  '/provider/setup': typeof AuthenticatedProviderSetupRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/reconciliation/booking/$bookingId': typeof AuthenticatedAdminReconciliationBookingBookingIdRoute
  '/admin/reconciliation/provider/$providerId': typeof AuthenticatedAdminReconciliationProviderProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/become-a-provider': typeof BecomeAProviderRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/provider': typeof AuthenticatedProviderRouteWithChildren
  '/_authenticated/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/admin/reconciliation': typeof AuthenticatedAdminReconciliationRouteWithChildren
  '/_authenticated/book/$category': typeof AuthenticatedBookCategoryRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/messages/$bookingId': typeof AuthenticatedMessagesBookingIdRoute
  '/_authenticated/provider/setup': typeof AuthenticatedProviderSetupRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/reconciliation/booking/$bookingId': typeof AuthenticatedAdminReconciliationBookingBookingIdRoute
  '/_authenticated/admin/reconciliation/provider/$providerId': typeof AuthenticatedAdminReconciliationProviderProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-a-provider'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/services'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/bookings'
    | '/dashboard'
    | '/notifications'
    | '/provider'
    | '/admin/commissions'
    | '/admin/providers'
    | '/admin/reconciliation'
    | '/book/$category'
    | '/bookings/$id'
    | '/messages/$bookingId'
    | '/provider/setup'
    | '/admin/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/reconciliation/booking/$bookingId'
    | '/admin/reconciliation/provider/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-a-provider'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/services'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/bookings'
    | '/dashboard'
    | '/notifications'
    | '/provider'
    | '/admin/commissions'
    | '/admin/providers'
    | '/admin/reconciliation'
    | '/book/$category'
    | '/bookings/$id'
    | '/messages/$bookingId'
    | '/provider/setup'
    | '/admin'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/reconciliation/booking/$bookingId'
    | '/admin/reconciliation/provider/$providerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/become-a-provider'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/services'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/bookings'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/provider'
    | '/_authenticated/admin/commissions'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/reconciliation'
    | '/_authenticated/book/$category'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/messages/$bookingId'
    | '/_authenticated/provider/setup'
    | '/_authenticated/admin/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/reconciliation/booking/$bookingId'
    | '/_authenticated/admin/reconciliation/provider/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BecomeAProviderRoute: typeof BecomeAProviderRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-provider': {
      id: '/become-a-provider'
      path: '/become-a-provider'
      fullPath: '/become-a-provider'
      preLoaderRoute: typeof BecomeAProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/provider': {
      id: '/_authenticated/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/provider/setup': {
      id: '/_authenticated/provider/setup'
      path: '/setup'
      fullPath: '/provider/setup'
      preLoaderRoute: typeof AuthenticatedProviderSetupRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    '/_authenticated/messages/$bookingId': {
      id: '/_authenticated/messages/$bookingId'
      path: '/messages/$bookingId'
      fullPath: '/messages/$bookingId'
      preLoaderRoute: typeof AuthenticatedMessagesBookingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
    '/_authenticated/book/$category': {
      id: '/_authenticated/book/$category'
      path: '/book/$category'
      fullPath: '/book/$category'
      preLoaderRoute: typeof AuthenticatedBookCategoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reconciliation': {
      id: '/_authenticated/admin/reconciliation'
      path: '/admin/reconciliation'
      fullPath: '/admin/reconciliation'
      preLoaderRoute: typeof AuthenticatedAdminReconciliationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/commissions': {
      id: '/_authenticated/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/reconciliation/provider/$providerId': {
      id: '/_authenticated/admin/reconciliation/provider/$providerId'
      path: '/provider/$providerId'
      fullPath: '/admin/reconciliation/provider/$providerId'
      preLoaderRoute: typeof AuthenticatedAdminReconciliationProviderProviderIdRouteImport
      parentRoute: typeof AuthenticatedAdminReconciliationRoute
    }
    '/_authenticated/admin/reconciliation/booking/$bookingId': {
      id: '/_authenticated/admin/reconciliation/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/admin/reconciliation/booking/$bookingId'
      preLoaderRoute: typeof AuthenticatedAdminReconciliationBookingBookingIdRouteImport
      parentRoute: typeof AuthenticatedAdminReconciliationRoute
    }
  }
}

interface AuthenticatedBookingsRouteChildren {
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
}

const AuthenticatedBookingsRouteChildren: AuthenticatedBookingsRouteChildren = {
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
}

const AuthenticatedBookingsRouteWithChildren =
  AuthenticatedBookingsRoute._addFileChildren(
    AuthenticatedBookingsRouteChildren,
  )

interface AuthenticatedProviderRouteChildren {
  AuthenticatedProviderSetupRoute: typeof AuthenticatedProviderSetupRoute
}

const AuthenticatedProviderRouteChildren: AuthenticatedProviderRouteChildren = {
  AuthenticatedProviderSetupRoute: AuthenticatedProviderSetupRoute,
}

const AuthenticatedProviderRouteWithChildren =
  AuthenticatedProviderRoute._addFileChildren(
    AuthenticatedProviderRouteChildren,
  )

interface AuthenticatedAdminReconciliationRouteChildren {
  AuthenticatedAdminReconciliationBookingBookingIdRoute: typeof AuthenticatedAdminReconciliationBookingBookingIdRoute
  AuthenticatedAdminReconciliationProviderProviderIdRoute: typeof AuthenticatedAdminReconciliationProviderProviderIdRoute
}

const AuthenticatedAdminReconciliationRouteChildren: AuthenticatedAdminReconciliationRouteChildren =
  {
    AuthenticatedAdminReconciliationBookingBookingIdRoute:
      AuthenticatedAdminReconciliationBookingBookingIdRoute,
    AuthenticatedAdminReconciliationProviderProviderIdRoute:
      AuthenticatedAdminReconciliationProviderProviderIdRoute,
  }

const AuthenticatedAdminReconciliationRouteWithChildren =
  AuthenticatedAdminReconciliationRoute._addFileChildren(
    AuthenticatedAdminReconciliationRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRouteWithChildren
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminReconciliationRoute: typeof AuthenticatedAdminReconciliationRouteWithChildren
  AuthenticatedBookCategoryRoute: typeof AuthenticatedBookCategoryRoute
  AuthenticatedMessagesBookingIdRoute: typeof AuthenticatedMessagesBookingIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProviderRoute: AuthenticatedProviderRouteWithChildren,
  AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
  AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
  AuthenticatedAdminReconciliationRoute:
    AuthenticatedAdminReconciliationRouteWithChildren,
  AuthenticatedBookCategoryRoute: AuthenticatedBookCategoryRoute,
  AuthenticatedMessagesBookingIdRoute: AuthenticatedMessagesBookingIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BecomeAProviderRoute: BecomeAProviderRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
